Add django env aa1 to implement aa1
snek-at/tastic-engine pull request #4
Opened 2020-07-30 10:51 UTC by pinterid

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [x] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [x] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently there is no environment for working with Django. #3 

**What is the new behavior (if this is a feature change)?**
- Now there is an environment to work with Djnago. #3 

**Other information**:
- Ref: 🐍

2020-07-30 10:54 UTC, Aichnerc approved these changes
LGTM 😘

2020-07-30 11:20 UTC, schettn commented
What you up to? Should this supposed to be a wagtail instance or just pure django?

2020-07-30 12:09 UTC, pinterid commented
It is supposed to be pure Django, because i prefer using it for the TASTIC monitoring tool. @schettn

2020-07-30 14:38 UTC, schettn requested changes
1. Have a look at my comment

2. Install black `pip3 install black` and run `black .` in the root of tastic-engine. Afterwards the whole code is formatted. Ref: [Black Formatter](https://www.google.com/search?client=safari&rls=en&q=python+black+formatter&ie=UTF-8&oe=UTF-8)
After installing Black it can also be chosen as formatter for VSCode.
3. The requirements.txt doesn't seem right. Run `pip3 freeze -> requirements.txt` to save all of your installed dependencies.

2020-07-30 14:38 UTC, schettn commented on .gitignore
> +env
I think that one is not really needed. Just choose windows-env or linux-venv when creating a virtual environment

2020-07-30 15:24 UTC, schettn approved these changes
✅

2020-07-31 08:17 UTC, kleberbaum approved these changes
Should be ok to merge.

2020-07-31 08:42 UTC, merged