Add landing page aa1 to implement aa1
snek-at/tastic-engine pull request #7
Opened 2020-07-31 13:55 UTC by pinterid

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [x] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently there is no landing page template for displaying:
  + The throughput chart of the last week
  + The burn down chart of the last week
  + The latest feature collection
  + The latest definition of done
  + The latest status report

**What is the new behavior (if this is a feature change)?**
- Now there is a landing page template for displaying:
  + The throughput chart of the last week
  + The burn down chart of the last week
  + The latest feature collection
  + The latest definition of done
  + The latest status report

**Other information**:
- Ref: https://getbootstrap.com/
- Ref: https://www.chartjs.org/

2020-07-31 14:41 UTC, Aichnerc approved these changes
Is ok, but check my note.

2020-07-31 14:41 UTC, Aichnerc commented on templates/footer.html
> +  <p></p>
Why?

2020-07-31 14:45 UTC, kleberbaum requested changes
Should be ok to merge after a few changes.

2020-07-31 14:45 UTC, kleberbaum commented on templates/footer.html
> +  <p></p>
```suggestion
```

2020-08-03 11:25 UTC, kleberbaum approved these changes
Should be ok to merge.

2020-08-03 11:25 UTC, schettn approved these changes
lgtm

2020-08-03 11:27 UTC, merged